# @Author: pipegalera
# @Date:   2020-11-02T12:07:42+01:00
# @Last modified by:   pipegalera
# @Last modified time: 2020-11-02T15:40:24+01:00



# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 20

# [[main]]
#  name = "Posts"
#  url = "#blog_posts"
#  weight = 30

[[main]]
  name = "Complete CV"
  url = "files/pipegalera.pdf"
  weight = 40
